language: generic

sudo: required

services:
  - docker


before_install:
  - docker build -t jmp/test-react -f Dockerfile.dev .
  
script:
  - docker run jmp/test-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-aws.us-east-1.aws.amazon.com"
  bucket_path: "docker-react"
  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

